//! §11/§11.1/§11.2/§12: generated-crate topology, the build-manifest schema, and driving
//! `cargo build` on the generated crate. WP-C5.1b's version of this proves the pipeline end to
//! end for the single-file, entry-only shape `emit_program` produces; splitting `src/main.rs`
//! into `stark_types.rs`/`stark_functions.rs`/etc. (§11) happens as generated programs grow
//! past WP-C5.1b's trivial case, and the stable `stark build` CLI/output path (§12.3) is
//! WP-C5.5a's job -- this module is invoked directly by tests today, not by a CLI command yet.

use super::{emit_program, BackendDiagnostic, NativeArtifact, NativeBuildOptions};
use crate::backend::version::{self, BuildVersions};
use crate::mir::MirProgram;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

pub fn build_and_link(
    program: &MirProgram,
    options: &NativeBuildOptions,
) -> Result<NativeArtifact, BackendDiagnostic> {
    let rustc_verbose = query_rustc_verbose()?;
    let rustc_version = parse_rustc_field(&rustc_verbose, "release: ")
        .ok_or_else(|| BackendDiagnostic::Io("could not parse `release:` from rustc -vV".into()))?
        .to_string();
    let target_triple = parse_rustc_field(&rustc_verbose, "host: ")
        .ok_or_else(|| BackendDiagnostic::Io("could not parse `host:` from rustc -vV".into()))?
        .to_string();
    let versions = version::build_versions(rustc_version, target_triple);

    let source = emit_program::emit(program, &versions)?;
    let build_key = compute_build_key(program, &versions);
    let crate_dir = options.target_dir.join("debug").join(&build_key);
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| BackendDiagnostic::Io(format!("creating {}: {e}", src_dir.display())))?;

    let runtime_path = runtime_crate_path();
    write_file(
        &crate_dir.join("Cargo.toml"),
        &generated_cargo_toml(&runtime_path),
    )?;
    write_file(&src_dir.join("main.rs"), &source.main_rs)?;
    write_file(
        &crate_dir.join("build.json"),
        &build_manifest_json(&versions, &build_key),
    )?;

    // §11.3 offline rule: `stark-runtime` is dependency-free, so `--offline` never needs a
    // registry index and proves no accidental network dependency crept in.
    let output = Command::new("cargo")
        .arg("build")
        .arg("--offline")
        .arg("--manifest-path")
        .arg(crate_dir.join("Cargo.toml"))
        .output()
        .map_err(|e| BackendDiagnostic::Io(format!("invoking cargo build: {e}")))?;
    if !output.status.success() {
        return Err(BackendDiagnostic::BuildFailed(format!(
            "generated-crate build failed:\n--- STDOUT ---\n{}\n--- STDERR ---\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        )));
    }

    let binary_path = crate_dir.join("target").join("debug").join(BIN_NAME);
    if !binary_path.exists() {
        return Err(BackendDiagnostic::BuildFailed(format!(
            "cargo build succeeded but the expected binary is missing at {}",
            binary_path.display()
        )));
    }

    Ok(NativeArtifact {
        binary_path,
        build_dir: crate_dir,
    })
}

const BIN_NAME: &str = "stark_program";

fn query_rustc_verbose() -> Result<String, BackendDiagnostic> {
    let output = Command::new("rustc").arg("-vV").output().map_err(|e| {
        BackendDiagnostic::Io(format!(
            "invoking `rustc -vV`: {e} (no Rust toolchain found -- WP-C5.5b's missing-toolchain \
             diagnostic supersedes this raw error)"
        ))
    })?;
    if !output.status.success() {
        return Err(BackendDiagnostic::Io(
            "`rustc -vV` did not succeed".to_string(),
        ));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn parse_rustc_field<'a>(verbose: &'a str, field: &str) -> Option<&'a str> {
    verbose.lines().find_map(|line| line.strip_prefix(field))
}

/// WP-C5.1b locates the runtime crate via this compiler build's own manifest directory. A real
/// installed toolchain needs a different discovery mechanism -- WP-C5.5c's job ("installation
/// and offline behaviour"), not reopened here.
fn runtime_crate_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("stark-runtime")
}

fn generated_cargo_toml(runtime_path: &Path) -> String {
    format!(
        "# GENERATED by the STARK native backend (WP-C5.1b). Do not edit.\n\
         [package]\n\
         name = \"stark-generated\"\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         # Cuts inheritance from any ancestor workspace (here, starkc's) -- a generated crate\n\
         # is its own workspace root, never a member of the compiler's own workspace.\n\
         [workspace]\n\
         \n\
         [[bin]]\n\
         name = \"{BIN_NAME}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         stark-runtime = {{ path = {:?} }}\n\
         \n\
         [profile.dev]\n\
         panic = \"abort\"\n",
        runtime_path,
    )
}

/// §11.1: source-content + version + target + profile hash, for build isolation/diagnostics
/// (explicitly not a security boundary, and not the incremental cache §11 says C5 doesn't need).
fn compute_build_key(program: &MirProgram, versions: &BuildVersions) -> String {
    let mut hasher = Sha256::new();
    hasher.update(program.dump().as_bytes());
    hasher.update(versions.compiler_version.as_bytes());
    hasher.update(versions.mir_version.as_bytes());
    hasher.update(versions.mir_runtime_surface.as_bytes());
    hasher.update(versions.runtime_version.as_bytes());
    hasher.update(versions.backend_version.as_bytes());
    hasher.update(versions.rustc_version.as_bytes());
    hasher.update(versions.target_triple.as_bytes());
    hasher.update(versions.profile.as_bytes());
    let digest = hasher.finalize();
    digest[..16].iter().map(|b| format!("{b:02x}")).collect()
}

fn build_manifest_json(versions: &BuildVersions, build_key: &str) -> String {
    format!(
        "{{\n  \"build_key\": {},\n  \"compiler_version\": {},\n  \"mir_version\": {},\n  \
         \"mir_runtime_surface\": {},\n  \"runtime_version\": {},\n  \"backend_version\": {},\n  \
         \"rustc_version\": {},\n  \"target_triple\": {},\n  \"profile\": {}\n}}\n",
        json_str(build_key),
        json_str(&versions.compiler_version),
        json_str(&versions.mir_version),
        json_str(&versions.mir_runtime_surface),
        json_str(&versions.runtime_version),
        json_str(&versions.backend_version),
        json_str(&versions.rustc_version),
        json_str(&versions.target_triple),
        json_str(&versions.profile),
    )
}

fn json_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

fn write_file(path: &Path, contents: &str) -> Result<(), BackendDiagnostic> {
    std::fs::write(path, contents)
        .map_err(|e| BackendDiagnostic::Io(format!("writing {}: {e}", path.display())))
}
