//! WP-C5.2b — function-body emission: real locals, assignments, copies, and moves for
//! `Copy`-classified scalar types (`emit_types::emit_ty`'s current scope is primitives only, so
//! every local this WP can even declare is `Copy`). Real place-based `Rvalue`s beyond `Use`
//! (arithmetic, aggregates), branches/loops, and calls are WP-C5.2c/d; this function is
//! extended then, not replaced.

use super::{emit_places, emit_types, BackendDiagnostic};
use crate::mir::{LocalKind, MirBody, Operand, Rvalue, Statement, Terminator};

/// Emits a function body for the WP-C5.2b-supported shape: a single real block (plus any number
/// of trivially-dead `Unreachable` trailer blocks -- WP-C4.5's synthetic return-slot lowering
/// appends one after every straight-line function, see `bb1` in `fn main() { }`'s own dump),
/// zero parameters, every local `Return`/`Param`/`User`/`Temp`-kinded, and every statement a
/// `Nop` or an assignment whose `Rvalue` is a plain `Use` of a constant or a place. Real
/// control flow (branches, loops, calls, non-`Use` rvalues) is WP-C5.2c/d.
pub fn emit_body(body: &MirBody) -> Result<String, BackendDiagnostic> {
    if !body.params.is_empty() {
        return Err(BackendDiagnostic::Unsupported(
            "WP-C5.2b supports only a zero-parameter entry body; parameters land in WP-C5.2d"
                .into(),
        ));
    }

    let entry_index = body.entry.0 as usize;
    let entry_block = body.blocks.get(entry_index).ok_or_else(|| {
        BackendDiagnostic::Unsupported("entry block index out of range".to_string())
    })?;
    for (bi, block) in body.blocks.iter().enumerate() {
        if bi == entry_index {
            continue;
        }
        let trivially_dead =
            block.statements.is_empty() && matches!(block.terminator.0, Terminator::Unreachable);
        if !trivially_dead {
            return Err(BackendDiagnostic::Unsupported(format!(
                "WP-C5.2b supports only an entry block plus trivially-dead `Unreachable` \
                 blocks; real multi-block control flow lands in WP-C5.2c (bb{bi} is not dead)"
            )));
        }
    }

    let mut out = String::from("{\n");

    // Every local is declared `let mut` up front, uninitialised, regardless of whether it is
    // ever reassigned after its first `Statement::Assign` -- this sidesteps tracking "is this
    // the first assignment" in the emitter (which would need a pre-pass once branches exist in
    // WP-C5.2c) at the cost of an always-`mut` declaration, which is harmless: the generated
    // file's `#![allow(unused)]` (emit_program.rs) already suppresses the `unused_mut` lint this
    // would otherwise trigger for a local assigned exactly once. Leaving a local truly
    // uninitialised (no `= ...` default) means rustc's own definite-assignment analysis rejects
    // a read-before-write generated by a lowering bug, rather than silently running with a
    // fabricated default value -- a safety property inherited for free at this scope.
    for (i, decl) in body.locals.iter().enumerate() {
        match &decl.kind {
            LocalKind::Return | LocalKind::Param(_) | LocalKind::User(_) | LocalKind::Temp => {}
            other => {
                return Err(BackendDiagnostic::Unsupported(format!(
                    "WP-C5.2b supports only Return/Param/User/Temp locals; {other:?} lands \
                     alongside indexing/Drop lowering (WP-C5.2c/C5.3)"
                )))
            }
        }
        let ty = emit_types::emit_ty(&decl.ty)?;
        out.push_str(&format!(
            "    let mut {}: {ty};\n",
            emit_places::local_name(i as u32)
        ));
    }

    for (stmt, _) in &entry_block.statements {
        match stmt {
            Statement::Nop => {}
            Statement::Assign(place, Rvalue::Use(operand)) => {
                let dest = emit_places::emit_place(place)?;
                let value = emit_operand(operand)?;
                out.push_str(&format!("    {dest} = {value};\n"));
            }
            other => {
                return Err(BackendDiagnostic::Unsupported(format!(
                    "WP-C5.2b supports only Nop statements and `Use`-rvalue assignments; \
                     {other:?} lands in WP-C5.2c"
                )))
            }
        }
    }

    match &entry_block.terminator.0 {
        Terminator::Return => {
            out.push_str(&format!("    {}\n", emit_places::local_name(0)));
        }
        other => {
            return Err(BackendDiagnostic::Unsupported(format!(
                "WP-C5.2b supports only a Return terminator; {other:?} lands in WP-C5.2c"
            )))
        }
    }
    out.push_str("}\n");
    Ok(out)
}

/// A `Copy`-classified scalar's `Move` is value-identical to its `Copy` -- WP-C5.2b only ever
/// declares `Copy` locals (`emit_types::emit_ty` admits primitives only, and every primitive
/// `MirTy` is `Copy` by construction, CLAUDE.md: "Copy requires all-Copy fields"), so both
/// operand kinds emit the same bare place reference here. Real non-`Copy` move/liveness tracking
/// (`WP-C5-ENTRY.md` §7.2's `MaybeUninit<ManuallyDrop<T>>` strategy) is deferred to whichever WP
/// first admits a non-`Copy` `MirTy` (WP-C5.3+).
fn emit_operand(operand: &Operand) -> Result<String, BackendDiagnostic> {
    match operand {
        Operand::Const(c) => emit_types::emit_constant(c),
        Operand::Copy(place) | Operand::Move(place) => emit_places::emit_place(place),
    }
}
