//! Top-level program emission: assembles the generated crate's `src/main.rs`. WP-C5.1b
//! supports exactly one shape -- a program consisting solely of the entry instance
//! (`mangle::ENTRY_SYMBOL`, matching `mir::interp::run_program`'s own lookup, per §5.2's "no
//! backend semantic reconstruction") with a trivial `Unit`-returning body. Direct/indirect
//! calls to other functions are WP-C5.2d.

use super::{emit_bodies, mangle, BackendDiagnostic};
use crate::mir::MirProgram;
use stark_runtime::version::BuildVersions;

pub struct GeneratedSource {
    pub main_rs: String,
}

pub fn emit(
    program: &MirProgram,
    versions: &BuildVersions,
) -> Result<GeneratedSource, BackendDiagnostic> {
    if program.bodies.len() != 1 {
        return Err(BackendDiagnostic::Unsupported(format!(
            "WP-C5.1b supports only a single-function (entry-only) program; direct/indirect \
             calls to other functions land in WP-C5.2d ({} bodies present)",
            program.bodies.len()
        )));
    }
    let entry = program
        .bodies
        .iter()
        .find(|b| b.instance.symbol == mangle::ENTRY_SYMBOL)
        .ok_or_else(|| {
            BackendDiagnostic::Unsupported(format!(
                "no `{}` instance in verified MIR -- every C5 program must have a monomorphised \
                 entry point",
                mangle::ENTRY_SYMBOL
            ))
        })?;
    let body_src = emit_bodies::emit_trivial_unit_body(entry)?;

    let mut main_rs = String::new();
    main_rs.push_str("// GENERATED by the STARK native backend (WP-C5.1b). Do not edit.\n");
    main_rs.push_str("#![allow(dead_code, unused)]\n\n");
    main_rs.push_str(&format!("// STARK instance: {}\n", entry.instance.symbol));
    main_rs.push_str("fn main() {\n");
    main_rs.push_str("    let __stark_build_versions = ");
    main_rs.push_str(&emit_build_versions_literal(versions));
    main_rs.push_str(";\n");
    main_rs.push_str(
        "    if let Err(mismatch) = stark_runtime::version::check(&__stark_build_versions) {\n",
    );
    main_rs.push_str("        eprintln!(\"stark-runtime version mismatch: generated for runtime {}, linked against {}\", mismatch.expected_runtime_version, mismatch.actual_runtime_version);\n");
    main_rs.push_str("        std::process::exit(1);\n");
    main_rs.push_str("    }\n");
    main_rs.push_str("    ");
    main_rs.push_str(&body_src);
    main_rs.push_str("}\n");

    Ok(GeneratedSource { main_rs })
}

fn emit_build_versions_literal(versions: &BuildVersions) -> String {
    format!(
        "stark_runtime::version::BuildVersions {{ \
         compiler_version: {}.to_string(), \
         mir_version: {}.to_string(), \
         mir_runtime_surface: {}.to_string(), \
         runtime_version: {}.to_string(), \
         backend_version: {}.to_string(), \
         rustc_version: {}.to_string(), \
         target_triple: {}.to_string(), \
         profile: {}.to_string() }}",
        rust_str_lit(&versions.compiler_version),
        rust_str_lit(&versions.mir_version),
        rust_str_lit(&versions.mir_runtime_surface),
        rust_str_lit(&versions.runtime_version),
        rust_str_lit(&versions.backend_version),
        rust_str_lit(&versions.rustc_version),
        rust_str_lit(&versions.target_triple),
        rust_str_lit(&versions.profile),
    )
}

/// A Rust string-literal token for an arbitrary host-reported string (rustc version, target
/// triple). These come from `rustc -vV`, not user source, but are escaped defensively rather
/// than trusted verbatim.
fn rust_str_lit(s: &str) -> String {
    format!("\"{}\"", s.escape_default())
}
