//! Top-level program emission: assembles the generated crate's `src/main.rs`. WP-C5.2d lifts
//! WP-C5.2b/c's single-function restriction -- every body in `program.bodies` (already a
//! self-contained, transitively-reachable set per `lower_program`'s own doc comment: "the entry
//! `main` plus every transitively-called supported function") is emitted as its own Rust `fn`.
//! The entry instance (`mangle::ENTRY_SYMBOL`, matching `mir::interp::run_program`'s own lookup,
//! per §5.2's "no backend semantic reconstruction") is still special-cased as Rust's literal
//! `fn main()` with the version-check prologue prepended; every other body goes through
//! `emit_bodies::emit_function` with its symbol's sanitized name. Indirect calls through a
//! function value remain WP-C5.4c.

use super::{emit_bodies, emit_projections, emit_types, mangle, BackendDiagnostic};
use crate::mir::{MirBody, MirProgram, MirTy};
use stark_runtime::version::BuildVersions;

pub struct GeneratedSource {
    pub main_rs: String,
}

pub fn emit(
    program: &MirProgram,
    versions: &BuildVersions,
    layout: &crate::layout::TargetLayout,
) -> Result<GeneratedSource, BackendDiagnostic> {
    let entry = program
        .bodies
        .iter()
        .find(|b| b.instance.symbol == mangle::ENTRY_SYMBOL)
        .ok_or_else(|| {
            BackendDiagnostic::Unsupported(format!(
                "no `{}` instance in verified MIR -- every C5 program must have a monomorphised \
                 entry point",
                mangle::ENTRY_SYMBOL
            ))
        })?;
    // Rust's `fn main()` takes no parameters and returns `()`; this is an entry-specific
    // constraint on the wrapper below, not a general property of `emit_bodies`, which stays
    // reusable for an arbitrary-signature ordinary function.
    if !matches!(entry.ret, MirTy::Unit) {
        return Err(BackendDiagnostic::Unsupported(
            "the entry instance must return Unit to become Rust's `fn main()`".to_string(),
        ));
    }
    if !entry.params.is_empty() {
        return Err(BackendDiagnostic::Unsupported(
            "the entry instance must take no parameters to become Rust's `fn main()`".to_string(),
        ));
    }

    let mut main_rs = String::new();
    main_rs.push_str("// GENERATED by the STARK native backend (WP-C5.2d). Do not edit.\n");
    main_rs.push_str("#![allow(dead_code, unused)]\n\n");

    // WP-C5.3a: §6.3's "one Rust definition per reachable concrete nominal instance", emitted
    // before every function so declaration order never depends on use order.
    main_rs.push_str(&emit_types::emit_nominal_definitions(program)?);

    // WP-C5.3d-0: the generated projection helpers, collected from the bodies below. Emitted
    // before them so the module is in scope, and so the ONE place unsafe appears in a generated
    // program is visible at the top of the file rather than buried.
    let projections = emit_projections::collect(program, layout)?;
    main_rs.push_str(&emit_projections::emit(&projections, &program.types)?);

    for body in &program.bodies {
        main_rs.push_str(&format!("// STARK instance: {}\n", body.instance.symbol));
        if body.instance.symbol == mangle::ENTRY_SYMBOL {
            main_rs.push_str(&emit_entry_fn(
                body,
                versions,
                &program.files,
                &program.types,
                layout,
            )?);
        } else {
            let name = mangle::function_name_for_symbol(&body.instance.symbol);
            main_rs.push_str(&emit_bodies::emit_function(
                body,
                &name,
                &program.files,
                &program.types,
                layout,
            )?);
        }
        main_rs.push('\n');
    }

    Ok(GeneratedSource { main_rs })
}

fn emit_entry_fn(
    entry: &MirBody,
    versions: &BuildVersions,
    files: &[std::sync::Arc<crate::source::SourceFile>],
    types: &crate::mir::TypeContext,
    layout: &crate::layout::TargetLayout,
) -> Result<String, BackendDiagnostic> {
    let block = emit_bodies::emit_block_body(entry, files, types, layout)?;
    let mut out = String::new();
    out.push_str("fn main() {\n");
    out.push_str("    let __stark_build_versions = ");
    out.push_str(&emit_build_versions_literal(versions));
    out.push_str(";\n");
    out.push_str(
        "    if let Err(mismatch) = stark_runtime::version::check(&__stark_build_versions) {\n",
    );
    out.push_str("        eprintln!(\"stark-runtime version mismatch: generated for runtime {}, linked against {}\", mismatch.expected_runtime_version, mismatch.actual_runtime_version);\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n");
    out.push_str("    ");
    out.push_str(&block);
    out.push_str("}\n");
    Ok(out)
}

fn emit_build_versions_literal(versions: &BuildVersions) -> String {
    format!(
        "stark_runtime::version::BuildVersions {{ \
         compiler_version: {}.to_string(), \
         mir_version: {}.to_string(), \
         mir_runtime_surface: {}.to_string(), \
         runtime_version: {}.to_string(), \
         backend_version: {}.to_string(), \
         rustc_version: {}.to_string(), \
         target_triple: {}.to_string(), \
         profile: {}.to_string() }}",
        rust_str_lit(&versions.compiler_version),
        rust_str_lit(&versions.mir_version),
        rust_str_lit(&versions.mir_runtime_surface),
        rust_str_lit(&versions.runtime_version),
        rust_str_lit(&versions.backend_version),
        rust_str_lit(&versions.rustc_version),
        rust_str_lit(&versions.target_triple),
        rust_str_lit(&versions.profile),
    )
}

/// A Rust string-literal token for an arbitrary host-reported string (rustc version, target
/// triple). These come from `rustc -vV`, not user source, but are escaped defensively rather
/// than trusted verbatim.
fn rust_str_lit(s: &str) -> String {
    format!("\"{}\"", s.escape_default())
}
