use starkc::onnx::{
    decode_signature, format_declaration, verify_declaration_source, DType, DecodeLimits,
    Dimension, DEFAULT_LIMITS,
};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicUsize, Ordering};

#[derive(Clone)]
enum Dim<'a> {
    Static(i64),
    Named(&'a str),
    Anonymous,
}

fn varint(mut value: u64) -> Vec<u8> {
    let mut bytes = Vec::new();
    loop {
        let mut byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            byte |= 0x80;
        }
        bytes.push(byte);
        if value == 0 {
            return bytes;
        }
    }
}

fn key(field: u32, wire: u8) -> Vec<u8> {
    varint((u64::from(field) << 3) | u64::from(wire))
}

fn scalar(field: u32, value: u64) -> Vec<u8> {
    let mut bytes = key(field, 0);
    bytes.extend(varint(value));
    bytes
}

fn message(field: u32, payload: &[u8]) -> Vec<u8> {
    let mut bytes = key(field, 2);
    bytes.extend(varint(payload.len() as u64));
    bytes.extend(payload);
    bytes
}

fn string(field: u32, value: &str) -> Vec<u8> {
    message(field, value.as_bytes())
}

fn dimension(dimension: &Dim<'_>) -> Vec<u8> {
    match dimension {
        Dim::Static(value) => scalar(1, *value as u64),
        Dim::Named(name) => string(2, name),
        Dim::Anonymous => Vec::new(),
    }
}

fn tensor_type(dtype: u64, dimensions: &[Dim<'_>]) -> Vec<u8> {
    let mut shape = Vec::new();
    for dim in dimensions {
        shape.extend(message(1, &dimension(dim)));
    }
    let mut tensor = scalar(1, dtype);
    tensor.extend(message(2, &shape));
    tensor
}

fn value(name: &str, dtype: u64, dimensions: &[Dim<'_>]) -> Vec<u8> {
    let mut info = string(1, name);
    info.extend(message(2, &message(1, &tensor_type(dtype, dimensions))));
    info
}

fn value_with_type(name: &str, type_proto: &[u8]) -> Vec<u8> {
    let mut info = string(1, name);
    info.extend(message(2, type_proto));
    info
}

fn initializer(name: &str) -> Vec<u8> {
    string(8, name)
}

fn model(inputs: &[Vec<u8>], outputs: &[Vec<u8>], initializers: &[Vec<u8>]) -> Vec<u8> {
    let mut graph = Vec::new();
    for item in initializers {
        graph.extend(message(5, item));
    }
    for item in inputs {
        graph.extend(message(11, item));
    }
    for item in outputs {
        graph.extend(message(12, item));
    }
    message(7, &graph)
}

fn representative_model() -> Vec<u8> {
    model(
        &[
            value(
                "image/input",
                1,
                &[
                    Dim::Named("batch-size"),
                    Dim::Static(3),
                    Dim::Static(224),
                    Dim::Static(224),
                ],
            ),
            value("weights", 1, &[Dim::Static(1000)]),
            value("mask", 9, &[Dim::Anonymous, Dim::Static(1)]),
        ],
        &[
            value(
                "class scores",
                1,
                &[Dim::Named("batch-size"), Dim::Static(1000)],
            ),
            value("valid", 9, &[Dim::Anonymous, Dim::Static(0)]),
        ],
        &[initializer("weights")],
    )
}

#[test]
fn decodes_order_types_dimensions_and_filters_initializer_inputs() {
    let signature = decode_signature(&representative_model(), DEFAULT_LIMITS).unwrap();
    assert_eq!(
        signature
            .inputs
            .iter()
            .map(|port| port.name.as_str())
            .collect::<Vec<_>>(),
        ["image/input", "mask"]
    );
    assert_eq!(
        signature
            .outputs
            .iter()
            .map(|port| port.name.as_str())
            .collect::<Vec<_>>(),
        ["class scores", "valid"]
    );
    assert_eq!(signature.inputs[0].dtype, DType::Float32);
    assert_eq!(signature.inputs[1].dtype, DType::Bool);
    assert_eq!(signature.outputs[1].dimensions[1], Dimension::Static(0));
    assert_eq!(
        signature.inputs[0].dimensions[0],
        signature.outputs[0].dimensions[0]
    );
    assert_ne!(
        signature.inputs[1].dimensions[0],
        signature.outputs[1].dimensions[0]
    );
}

#[test]
fn generation_is_stable_parseable_and_verifiable() {
    let artifact = representative_model();
    let signature = decode_signature(&artifact, DEFAULT_LIMITS).unwrap();
    let generated = format_declaration(
        &signature,
        "12-resnet.demo",
        "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    );
    let expected = format!(
        concat!(
            "// Generated by starkc {}; ONNX SHA-256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef\n",
            "// starkc-onnx-name input image_input 696d6167652f696e707574\n",
            "// starkc-onnx-name output class_scores 636c6173732073636f726573\n",
            "\n",
            "model Model12ResnetDemo<batch_size: Dim, D2: Dim, D3: Dim> {{\n",
            "    input image_input: Tensor<Float32, [batch_size, 3, 224, 224]>;\n",
            "    input mask: Tensor<Bool, [D2, 1]>;\n",
            "    output class_scores: Tensor<Float32, [batch_size, 1000]>;\n",
            "    output valid: Tensor<Bool, [D3, 0]>;\n",
            "}}\n",
        ),
        env!("CARGO_PKG_VERSION")
    );
    assert_eq!(generated, expected);
    assert!(generated.starts_with("// Generated by starkc "));
    assert!(generated.contains("model Model12ResnetDemo<batch_size: Dim, D2: Dim, D3: Dim>"));
    assert!(generated.contains("// starkc-onnx-name input image_input 696d6167652f696e707574"));
    assert!(generated.ends_with("}\n"));
    assert!(!generated.ends_with("\n\n"));
    assert!(
        verify_declaration_source(&signature, &generated, "generated.stark", None)
            .unwrap()
            .is_match()
    );
}

#[test]
fn verification_accumulates_signature_drift() {
    let signature = decode_signature(&representative_model(), DEFAULT_LIMITS).unwrap();
    let declaration = r#"
model Drift<A: Dim, B: Dim, C: Dim> {
    input wrong_name: Tensor<Float16, [A, 3, 225, 224]>;
    input mask: Tensor<Bool, [A, 1]>;
    output class_scores: Tensor<Float32, [B, 999]>;
    output valid: Tensor<Bool, [C]>;
}
"#;
    let report = verify_declaration_source(&signature, declaration, "drift.stark", None).unwrap();
    let joined = report.differences.join("\n");
    assert!(joined.contains("name differs"), "{joined}");
    assert!(joined.contains("dtype differs"), "{joined}");
    assert!(joined.contains("dimension 2 differs"), "{joined}");
    assert!(
        joined.contains("multiple artifact dynamic identities"),
        "{joined}"
    );
    assert!(
        joined.contains("artifact dynamic identity used by declaration dimensions"),
        "{joined}"
    );
    assert!(joined.contains("rank differs"), "{joined}");
}

#[test]
fn verification_reports_counts_rank_and_static_dynamic_classification() {
    let signature = decode_signature(
        &model(
            &[value("x", 1, &[Dim::Static(7), Dim::Named("N")])],
            &[value("y", 1, &[Dim::Named("N"), Dim::Static(2)])],
            &[],
        ),
        DEFAULT_LIMITS,
    )
    .unwrap();
    let declaration = r#"
model Drift<A: Dim> {
    input x: Tensor<Float32, [A, 1]>;
    output y: TensorDyn<Float32>;
    output extra: Tensor<Float32, [1]>;
}
"#;
    let report = verify_declaration_source(&signature, declaration, "drift.stark", None).unwrap();
    let joined = report.differences.join("\n");
    assert!(joined.contains("output port count differs"), "{joined}");
    assert!(joined.contains("over-promises dynamic"), "{joined}");
    assert!(
        joined.contains("dynamic in the artifact but static"),
        "{joined}"
    );
    assert!(joined.contains("is TensorDyn"), "{joined}");
}

#[test]
fn verifier_requires_unambiguous_model_selection() {
    let signature = decode_signature(
        &model(
            &[value("x", 1, &[Dim::Static(1)])],
            &[value("y", 1, &[Dim::Static(1)])],
            &[],
        ),
        DEFAULT_LIMITS,
    )
    .unwrap();
    let source = "model A { input x: Tensor<Float32, [1]>; output y: Tensor<Float32, [1]>; }\n\
                  model B { input x: Tensor<Float32, [1]>; output y: Tensor<Float32, [1]>; }\n";
    let error = verify_declaration_source(&signature, source, "models.stark", None).unwrap_err();
    assert!(error.to_string().contains("multiple models"));
    assert!(
        verify_declaration_source(&signature, source, "models.stark", Some("B"))
            .unwrap()
            .is_match()
    );
    let error =
        verify_declaration_source(&signature, source, "models.stark", Some("Missing")).unwrap_err();
    assert!(error.to_string().contains("available models: `A`, `B`"));
}

#[test]
fn rejects_malformed_and_unsupported_metadata_without_panicking() {
    let unsupported_dtype = model(
        &[value("x", 8, &[Dim::Static(1)])],
        &[value("y", 1, &[Dim::Static(1)])],
        &[],
    );
    let unsupported_sequence = model(
        &[value_with_type("x", &message(4, &[]))],
        &[value("y", 1, &[Dim::Static(1)])],
        &[],
    );
    let missing_type = model(&[string(1, "x")], &[value("y", 1, &[Dim::Static(1)])], &[]);
    let missing_shape = model(
        &[value_with_type("x", &message(1, &scalar(1, 1)))],
        &[value("y", 1, &[Dim::Static(1)])],
        &[],
    );
    let negative = model(
        &[value("x", 1, &[Dim::Static(-1)])],
        &[value("y", 1, &[Dim::Static(1)])],
        &[],
    );
    let empty = model(
        &[value("", 1, &[Dim::Static(1)])],
        &[value("y", 1, &[Dim::Static(1)])],
        &[],
    );
    let duplicate = model(
        &[value("x", 1, &[]), value("x", 1, &[])],
        &[value("y", 1, &[])],
        &[],
    );
    let cross_direction_duplicate = model(&[value("same", 1, &[])], &[value("same", 1, &[])], &[]);
    for (bytes, expected) in [
        (unsupported_dtype, "unsupported ONNX tensor element type 8"),
        (unsupported_sequence, "unsupported ONNX sequence graph port"),
        (missing_type, "missing its TypeProto"),
        (missing_shape, "missing its rank/shape"),
        (negative, "negative"),
        (empty, "empty name"),
        (duplicate, "duplicate input port"),
        (cross_direction_duplicate, "duplicate external port `same`"),
        (vec![0x3a, 0x80], "truncated protobuf varint"),
        (vec![0x00], "field number zero"),
        (vec![0x3b], "field 7 has wire type 3, expected 2"),
    ] {
        let result = std::panic::catch_unwind(|| decode_signature(&bytes, DEFAULT_LIMITS));
        let error = result.expect("malformed ONNX must not panic").unwrap_err();
        assert!(error.to_string().contains(expected), "{error:?}");
    }
}

#[test]
fn short_corrupt_and_truncated_inputs_never_panic() {
    let valid = representative_model();
    for length in 0..valid.len() {
        let prefix = &valid[..length];
        assert!(
            std::panic::catch_unwind(|| decode_signature(prefix, DEFAULT_LIMITS)).is_ok(),
            "decoder panicked for prefix length {length}"
        );
    }
    for byte in 0u8..=u8::MAX {
        assert!(
            std::panic::catch_unwind(|| decode_signature(&[byte], DEFAULT_LIMITS)).is_ok(),
            "decoder panicked for single byte {byte:#04x}"
        );
    }
}

#[test]
fn enforces_configured_decoder_boundaries() {
    let one = model(
        &[value("x", 1, &[Dim::Static(1)])],
        &[value("y", 1, &[Dim::Static(1)])],
        &[initializer("w")],
    );
    let exact_file = DecodeLimits {
        max_file_size: one.len(),
        ..DEFAULT_LIMITS
    };
    assert!(decode_signature(&one, exact_file).is_ok());
    assert!(decode_signature(
        &one,
        DecodeLimits {
            max_file_size: one.len() - 1,
            ..DEFAULT_LIMITS
        }
    )
    .unwrap_err()
    .to_string()
    .contains("file exceeds"));

    let limits = DecodeLimits {
        max_inputs: 1,
        max_outputs: 1,
        max_initializers: 1,
        max_rank: 1,
        max_name_bytes: 1,
        max_depth: 6,
        ..DEFAULT_LIMITS
    };
    assert!(decode_signature(&one, limits).is_ok());
    let two_inputs = model(
        &[value("x", 1, &[]), value("z", 1, &[])],
        &[value("y", 1, &[])],
        &[],
    );
    assert!(decode_signature(&two_inputs, limits)
        .unwrap_err()
        .to_string()
        .contains("input limit"));
    let two_outputs = model(
        &[value("x", 1, &[])],
        &[value("y", 1, &[]), value("z", 1, &[])],
        &[],
    );
    assert!(decode_signature(&two_outputs, limits)
        .unwrap_err()
        .to_string()
        .contains("output limit"));
    let duplicate_initializers = model(
        &[value("x", 1, &[])],
        &[value("y", 1, &[])],
        &[initializer("w"), initializer("w")],
    );
    assert!(decode_signature(&duplicate_initializers, limits)
        .unwrap_err()
        .to_string()
        .contains("initializer limit"));
    let rank_two = model(
        &[value("x", 1, &[Dim::Static(1), Dim::Static(2)])],
        &[value("y", 1, &[])],
        &[],
    );
    assert!(decode_signature(&rank_two, limits)
        .unwrap_err()
        .to_string()
        .contains("rank exceeds"));
    let long_name = model(&[value("xx", 1, &[])], &[value("y", 1, &[])], &[]);
    assert!(decode_signature(&long_name, limits)
        .unwrap_err()
        .to_string()
        .contains("name exceeds"));
    assert!(decode_signature(
        &one,
        DecodeLimits {
            max_depth: 5,
            ..DEFAULT_LIMITS
        }
    )
    .unwrap_err()
    .to_string()
    .contains("nesting depth"));
    assert!(decode_signature(
        &one,
        DecodeLimits {
            max_field_size: one.len() - 3,
            ..DEFAULT_LIMITS
        }
    )
    .unwrap_err()
    .to_string()
    .contains("field exceeds"));
}

static NEXT_TEMP: AtomicUsize = AtomicUsize::new(0);

struct TempDir(PathBuf);

impl TempDir {
    fn new() -> Self {
        let serial = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
        let path =
            std::env::temp_dir().join(format!("starkc-onnx-{}-{serial}", std::process::id()));
        fs::create_dir(&path).unwrap();
        Self(path)
    }

    fn join(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn starkc(arguments: &[&Path]) -> Output {
    let mut command = Command::new(env!("CARGO_BIN_EXE_starkc"));
    for argument in arguments {
        command.arg(argument);
    }
    command.output().unwrap()
}

#[test]
fn cli_import_verify_overwrite_and_exit_statuses() {
    let temp = TempDir::new();
    let artifact = temp.join("tiny-model.onnx");
    let declaration = temp.join("tiny-model.stark");
    fs::write(&artifact, representative_model()).unwrap();

    let imported = starkc(&[
        Path::new("import"),
        &artifact,
        Path::new("--out"),
        &declaration,
    ]);
    assert!(
        imported.status.success(),
        "{}",
        String::from_utf8_lossy(&imported.stderr)
    );
    let source = fs::read_to_string(&declaration).unwrap();
    assert!(source.contains("ONNX SHA-256:"));

    let refused = starkc(&[
        Path::new("import"),
        &artifact,
        Path::new("--out"),
        &declaration,
    ]);
    assert_eq!(refused.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&refused.stderr).contains("already exists"));
    let forced = starkc(&[
        Path::new("import"),
        &artifact,
        Path::new("--out"),
        &declaration,
        Path::new("--force"),
    ]);
    assert!(forced.status.success());

    let verified = starkc(&[
        Path::new("verify"),
        &artifact,
        Path::new("--declaration"),
        &declaration,
    ]);
    assert!(
        verified.status.success(),
        "{}",
        String::from_utf8_lossy(&verified.stderr)
    );

    fs::write(&declaration, source.replace("Float32", "Float16")).unwrap();
    let mismatch = starkc(&[
        Path::new("verify"),
        &artifact,
        Path::new("--declaration"),
        &declaration,
    ]);
    assert_eq!(mismatch.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&mismatch.stderr).contains("dtype differs"));

    let usage = starkc(&[Path::new("import"), &artifact]);
    assert_eq!(usage.status.code(), Some(2));
    let missing_value = starkc(&[
        Path::new("import"),
        &artifact,
        Path::new("--out"),
        Path::new("--force"),
    ]);
    assert_eq!(missing_value.status.code(), Some(2));
    let duplicate_flag = starkc(&[
        Path::new("verify"),
        &artifact,
        Path::new("--declaration"),
        &declaration,
        Path::new("--declaration"),
        &declaration,
    ]);
    assert_eq!(duplicate_flag.status.code(), Some(2));
}
