//! **WP-ARCH-CLOSE AC2 — the executable native conformance contract.**
//!
//! `Native = done — qualified subset` requires institutional knowledge to interpret. This test
//! replaces that sentence with a generated table an external developer can read: for each Core
//! construct, which stages accept it, whether it runs natively, and — when it does not — what
//! refuses it and which DEV owns the boundary.
//!
//! **The matrix is not a document that describes behaviour. It is generated FROM behaviour**, and
//! CI fails in both directions:
//!
//! ```text
//! compiler behaviour changes + published matrix unchanged   ->  this test FAILS
//! published matrix edited    + probe evidence disagrees     ->  this test FAILS
//! ```
//!
//! There is no third state where the file and the compiler quietly differ. To update the published
//! matrix, change the compiler (or the probe inventory) and regenerate:
//!
//! ```text
//! STARK_REGENERATE_CONFORMANCE_MATRIX=1 cargo test --test native_conformance_matrix
//! ```
//!
//! **Every cell is measured on this run.** No cell is transcribed from `KNOWN-DEVIATIONS.md`,
//! `COMPILER-STATE.md`, or any prior report — those record what was true when they were written,
//! and AC2 exists because a developer cannot be asked to read them. The DEV ids in the last column
//! come from the probe inventory's registration and are the one exception: they are *pointers to*
//! an owner, not claims about behaviour, and `layer_audit` independently enforces that each still
//! reproduces.
//!
//! ## What the columns mean, and what they do not
//!
//! `Parser` … `MIR verify` are this process's own stages. `Native debug` / `Native release` are a
//! real `rustc` build and a real execution of the produced binary. **A row is `SUPPORTED` only when
//! every engine agreed on the full normative observation** — stdout bytes, exit status, drop log,
//! trap category and location — through the same comparator the C6 differential suites use
//! (`support::differential::compare_observations`). Agreement alone is not the standard: the probe
//! inventory is shared with `layer_audit`, which pins each probe's expected disposition
//! independently.
//!
//! **`Tier-1` is a statement about where this test runs, not a separate measurement.** The matrix
//! content is platform-independent by construction, and CI runs `cargo test` on all three Tier-1
//! platforms — so a construct that behaved differently on one of them would fail this test there.
//! That is the whole of the claim; it is not evidence about platforms CI does not run.

mod support;

use starkc::backend::generated_rust::Profile;
use starkc::mir::lower::lower_program;
use starkc::mir::verify::verify_program;
use std::path::PathBuf;
use support::differential::{
    compare_observations, run_hir, run_mir, run_native_with_profile, rustc_available, Observation,
};
use support::layer_probes::{measure, probes, Expect, Stage};

/// The published contract. Regenerated by this test; never hand-edited.
fn matrix_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("docs")
        .join("conformance")
        .join("NATIVE-CONFORMANCE-MATRIX.md")
}

/// AC2's allowed statuses. `DEFERRED` and `NOT-APPLICABLE` are unused by the current inventory and
/// are deliberately still listed in the published legend: a status vocabulary that only contains
/// the values currently in use tells a reader nothing about what else could appear.
#[derive(Debug, PartialEq, Eq)]
enum Status {
    Supported,
    RefusedByDesign,
    KnownDeviation,
}

impl Status {
    fn cell(&self) -> &'static str {
        match self {
            Status::Supported => "SUPPORTED",
            Status::RefusedByDesign => "REFUSED-BY-DESIGN",
            Status::KnownDeviation => "KNOWN-DEVIATION",
        }
    }
}

struct Row {
    construct: String,
    parse: String,
    resolve: String,
    typecheck: String,
    hir_exec: String,
    mir_lower: String,
    mir_verify: String,
    mir_exec: String,
    native_debug: String,
    native_release: String,
    status: Status,
    limitation: String,
}

/// The refusal's owning phase, in a form a reader can act on: the diagnostic code where there is
/// one, and the phase otherwise. **Truncated deliberately** — the full lowering message is an
/// implementation string, and pinning it in a published contract would make every internal
/// rewording a matrix change.
fn refusal_summary(m: &support::layer_probes::StageMeasurement) -> String {
    let raw = m.refusal().unwrap_or("(none)");
    // Front-end refusals begin with their diagnostic code; lowering refusals do not have one.
    let first_token = raw.split_whitespace().next().unwrap_or("");
    if first_token.starts_with('E') && first_token[1..].chars().all(|c| c.is_ascii_digit()) {
        format!("`{first_token}` at type check")
    } else if raw.starts_with("parse:") {
        "refused by the parser".to_string()
    } else if raw.starts_with("resolve:") {
        "refused by name resolution".to_string()
    } else if matches!(m.mir_lower, Stage::Refused(_)) {
        "refused by MIR lowering".to_string()
    } else {
        "refused by the front end".to_string()
    }
}

#[test]
fn the_published_native_conformance_matrix_matches_measured_behaviour() {
    if !rustc_available() {
        // The repo's SKIP convention: `run-c64-qualification.py` detects this line with
        // `--nocapture` and fails the required step, so a toolchain-less machine cannot report a
        // green matrix having built nothing.
        eprintln!("SKIP: no rustc in this environment; the native columns cannot be measured.");
        return;
    }

    let mut rows: Vec<Row> = Vec::new();

    for entry in probes() {
        let m = measure(entry.source);

        // Every stage after the refusal is `—`, and the columns say so rather than reading blank.
        let mut row = Row {
            construct: entry.construct.replace('|', "\\|"),
            parse: m.parse.cell().to_string(),
            resolve: m.resolve.cell().to_string(),
            typecheck: m.typecheck.cell().to_string(),
            hir_exec: "--".to_string(),
            mir_lower: m.mir_lower.cell().to_string(),
            mir_verify: "--".to_string(),
            mir_exec: "--".to_string(),
            native_debug: "--".to_string(),
            native_release: "--".to_string(),
            status: Status::RefusedByDesign,
            limitation: String::new(),
        };

        match entry.expect {
            Expect::FrontEnd => {
                assert!(
                    m.refusal().is_some(),
                    "{}: registered as a front-end refusal but nothing refused it. The probe \
                     inventory and the compiler disagree; `layer_audit` owns that reconciliation.",
                    entry.label
                );
                row.status = Status::RefusedByDesign;
                row.limitation = refusal_summary(&m);
            }
            Expect::KnownDev(dev) => {
                assert!(
                    matches!(m.mir_lower, Stage::Refused(_)),
                    "{}: registered as {dev}, a reachable lowering refusal, but lowering did not \
                     refuse it. `layer_audit` owns that reconciliation.",
                    entry.label
                );
                row.status = Status::KnownDeviation;
                // The shape AC2 §6.4 requires for an unsupported native boundary: the refusal is
                // STARK-owned, deterministic, and named. It is a compile-time refusal, so no
                // program observes it at runtime.
                row.limitation = format!(
                    "{dev} — {}, before any code is emitted",
                    refusal_summary(&m)
                );
            }
            Expect::Lowers => {
                assert!(
                    m.refusal().is_none(),
                    "{}: registered as lowering cleanly, but it was {}.",
                    entry.label,
                    refusal_summary(&m)
                );
                row.status = Status::Supported;
                row.limitation = "--".to_string();
            }
        }

        if entry.execute {
            assert!(
                matches!(row.status, Status::Supported),
                "{}: marked for execution but not a supported construct",
                entry.label
            );
            let observed = execute_through_every_engine(entry.label, entry.source);
            row.hir_exec = observed.clone();
            row.mir_verify = "pass".to_string();
            row.mir_exec = observed.clone();
            row.native_debug = observed.clone();
            row.native_release = observed;
        }

        rows.push(row);
    }

    let generated = render(&rows);
    let path = matrix_path();

    if std::env::var("STARK_REGENERATE_CONFORMANCE_MATRIX").is_ok() {
        std::fs::create_dir_all(path.parent().expect("has a parent")).expect("create docs dir");
        std::fs::write(&path, &generated).expect("write the matrix");
        eprintln!("regenerated {}", path.display());
        return;
    }

    let published = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "the published native conformance matrix is missing at {} ({e}). Generate it with \
             STARK_REGENERATE_CONFORMANCE_MATRIX=1 cargo test --test native_conformance_matrix",
            path.display()
        )
    });

    // CRLF normalised at the read: a Windows checkout must not change the comparison.
    if published.replace("\r\n", "\n") != generated {
        let difference = first_differing_line(&published.replace("\r\n", "\n"), &generated);
        panic!(
            "THE PUBLISHED NATIVE CONFORMANCE MATRIX NO LONGER MATCHES MEASURED BEHAVIOUR.\n\n\
             {difference}\n\n\
             This fires in both directions, and neither is a formatting complaint:\n\
             \x20 - the compiler changed and the contract was not regenerated, or\n\
             \x20 - the contract was edited and the compiler does not agree.\n\n\
             The matrix is generated, never hand-edited. Regenerate it in the same change as \
             whatever moved the behaviour:\n\n\
             \x20 STARK_REGENERATE_CONFORMANCE_MATRIX=1 cargo test --test native_conformance_matrix\n\n\
             If a construct's support changed, the owning DEV entry needs updating too."
        );
    }
}

/// Runs one supported construct through all four engine configurations and requires identical
/// normative observations. Returns the cell text every engine column carries.
fn execute_through_every_engine(label: &str, source: &str) -> String {
    let name = format!("matrix_{}.stark", sanitise(label));
    let front = support::differential::front_end(&name, source);
    let program =
        lower_program(&front.hir, &front.tables, front.file.clone()).unwrap_or_else(|e| {
            panic!(
                "{label}: lowering failed after measuring as lowering: {}",
                e.what
            )
        });
    verify_program(&program)
        .unwrap_or_else(|e| panic!("{label}: the MIR verifier rejected lowered MIR: {e:#?}"));

    let tag = sanitise(label);
    let hir = run_hir(&name, &front);
    let mir = run_mir(&name, &program);
    let native = run_native_with_profile(&name, &tag, &program, Profile::Debug);
    let release =
        run_native_with_profile(&name, &format!("{tag}_release"), &program, Profile::Release);

    if let Err(disagreement) = compare_observations(&name, &hir, &mir, &native) {
        panic!(
            "{label}: the engines disagree, so this construct is NOT supported:\n{disagreement}"
        );
    }
    assert_eq!(
        native, release,
        "{label}: native debug and release disagree, so this construct is NOT supported"
    );

    // What the cell says. A completing program's exit status is the honest summary; a construct
    // whose probe trapped would be recorded as its category instead.
    match &hir {
        Observation::Completed(done) => format!("runs (exit {})", done.exit_status),
        Observation::Trapped(trap) => format!("traps ({:?})", trap.category),
    }
}

fn sanitise(label: &str) -> String {
    label
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn first_differing_line(published: &str, generated: &str) -> String {
    for (i, (p, g)) in published.lines().zip(generated.lines()).enumerate() {
        if p != g {
            return format!(
                "First difference at line {}:\n  published: {p}\n  measured:  {g}",
                i + 1
            );
        }
    }
    format!(
        "The files agree line by line but differ in length: published {} lines, measured {}.",
        published.lines().count(),
        generated.lines().count()
    )
}

fn render(rows: &[Row]) -> String {
    let supported = rows
        .iter()
        .filter(|r| r.status == Status::Supported)
        .count();
    let refused = rows
        .iter()
        .filter(|r| r.status == Status::RefusedByDesign)
        .count();
    let deviations = rows
        .iter()
        .filter(|r| r.status == Status::KnownDeviation)
        .count();
    let executed = rows.iter().filter(|r| r.native_debug != "--").count();

    let mut out = String::new();
    out.push_str(
        r#"# Native conformance matrix

**Generated. Do not edit.** Produced by `starkc/tests/native_conformance_matrix.rs` from a live
compiler run, and validated by that test on every CI run on all three Tier-1 platforms. Editing this
file by hand fails CI; so does changing the compiler without regenerating it.

```text
STARK_REGENERATE_CONFORMANCE_MATRIX=1 cargo test --test native_conformance_matrix
```

## What this answers

*Is this construct supported by the native compiler, and if not, what happens when I write it?* You
should not need `COMPILER-STATE.md`, the deviation ledger, or the compiler source to answer that.

Every cell below was measured on the run that generated this file. No cell is transcribed from a
report.

## Statuses

```text
SUPPORTED          every stage accepts it, and all four engine configurations -- HIR oracle,
                   MIR interpreter, native debug, native release -- produced the SAME
                   normative observation: stdout bytes, exit status, drop log, and any
                   trap's category and location

REFUSED-BY-DESIGN  STARK refuses it, deliberately, at a named stage. Writing it gives you a
                   STARK diagnostic at compile time -- never a rustc error, and never wrong
                   behaviour at run time

KNOWN-DEVIATION    the front end accepts it and MIR lowering refuses it. Valid STARK that this
                   compiler cannot build. The refusal is STARK's own and arrives before any
                   code is emitted, and the owning DEV is named

DEFERRED           scheduled, not yet implemented (no row currently carries this)

NOT-APPLICABLE     the stage has no meaning for this construct (no row currently carries this)
```

A `--` cell means the stage was never reached, because an earlier one refused the program. It does
**not** mean the stage accepted it.

"#,
    );
    out.push_str(&format!(
        r#"## Summary

```text
constructs measured       {}
SUPPORTED                 {}   of which {} were executed through all four engine
                               configurations and compared
REFUSED-BY-DESIGN         {}
KNOWN-DEVIATION           {}
```

**This is a boundary inventory, not a census of the language.** Every row is a construct chosen
because it sits at or near an edge of the supported subset -- that is what makes the boundary
legible. A construct absent from this table is not thereby unsupported; the core language beyond
these edges is covered by the conformance corpus and the differential suites. What this table is
authoritative about is the edges themselves.

"#,
        rows.len(),
        supported,
        executed,
        refused,
        deviations,
    ));
    out.push_str(
        "## The matrix\n\
         \n\
         | Construct | Parse | Resolve | Typecheck | HIR exec | MIR lower | MIR verify | MIR exec | Native debug | Native release | Status | Limitation / DEV |\n\
         | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for r in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | **{}** | {} |\n",
            r.construct,
            r.parse,
            r.resolve,
            r.typecheck,
            r.hir_exec,
            r.mir_lower,
            r.mir_verify,
            r.mir_exec,
            r.native_debug,
            r.native_release,
            r.status.cell(),
            r.limitation,
        ));
    }
    out.push_str(
        r#"
## Tier-1 platforms

This matrix is platform-independent by construction, and the test that generates it runs in CI's
`fmt, clippy, test` job on **linux-x64, macos-arm64 and windows-x64**. A construct that behaved
differently on one of those would fail this test on that platform, rather than appearing here as a
footnote.

That is the entire Tier-1 claim. It is not evidence about any platform CI does not run.

## What this matrix does not tell you

- **It is not a completeness claim.** See the summary note above: these are boundary constructs,
  not the whole language.
- **A `KNOWN-DEVIATION` row is valid STARK.** It is refused by this compiler, not by the
  specification. Each names the DEV that owns the gap; the deviation ledger records why the repair
  is deferred, and what a working spelling is where one exists.
- **`SUPPORTED` means the four configurations agreed on this probe**, not that every program using
  the construct is correct. Agreement is checked against the shared comparator; the probe's own
  expectation is pinned separately by `layer_audit`, so a construct is not called supported merely
  because every engine is wrong about it in the same way.
"#,
    );
    out
}
