#!/usr/bin/env python3
"""WP-C6.5 corpus tool — lock generation today, case generation from C6.5-4 (§11).

Two modes, both deterministic and offline:

    python3 generate.py --lock     rewrite corpus.lock from the corpus on disk
    python3 generate.py --check    exit 1 if corpus.lock is stale (what CI would ask)

The lock is regenerated by a checked-in script rather than by hand because §9.5 requires per-source
hashes plus counts that must agree with the manifest, and a hand-maintained hash list is a hash list
that silently stops matching. The script is itself hashed into the lock (`generator_sha256`), so
changing how the corpus is generated invalidates the lock — which is the point: the lock pins the
corpus AND the thing that produced it.

Determinism rules this script follows, so two machines produce byte-identical output:
  * paths are corpus-root-relative, `/`-separated, and sorted with plain byte ordering;
  * files are read as bytes, never decoded, so no locale or newline translation can enter;
  * the output ends with exactly one newline and uses LF throughout.
"""

import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
CORPUS_VERSION = "0.1.0"
# Set once the C6.5-4 generator exists; until then no case is generated, and saying "unset" is more
# honest than recording a seed nothing was produced from.
GENERATOR_SEED = "unset-until-c6.5-4"


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sources() -> list[str]:
    """Every corpus source, root-relative and sorted. `.stark` only: the manifest, lock, README and
    this script are corpus infrastructure, hashed separately rather than counted as cases."""
    found = [p.relative_to(ROOT).as_posix() for p in ROOT.rglob("*.stark")]
    return sorted(found)


def parse_manifest() -> list[dict]:
    """The same small strict subset the Rust reader accepts (§9.4): `[[case]]` headers and
    `key = "string" | ["a", "b"] | true`. Kept deliberately simple — if this needs a real TOML
    parser, the manifest has outgrown its schema and that is the thing to fix."""
    cases: list[dict] = []
    for number, raw in enumerate(
        (ROOT / "manifest.toml").read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == "[[case]]":
            cases.append({})
            continue
        if " = " not in line:
            raise SystemExit(f"manifest.toml line {number}: not a `key = value` line: {line!r}")
        key, value = line.split(" = ", 1)
        if not cases:
            raise SystemExit(f"manifest.toml line {number}: `{key}` before any [[case]]")
        value = value.strip()
        if value in ("true", "false"):
            cases[-1][key] = value == "true"
        elif value.startswith("[") and value.endswith("]"):
            body = value[1:-1].strip()
            cases[-1][key] = (
                [item.strip().strip('"') for item in body.split(",")] if body else []
            )
        else:
            cases[-1][key] = value.strip('"')
    return cases


def build_lock() -> str:
    cases = parse_manifest()
    kinds = [case.get("kind", "") for case in cases]
    groups = {case["metamorphic_group"] for case in cases if "metamorphic_group" in case}
    lines = [
        "# WP-C6.5 differential corpus lock (§9.5). Generated by `generate.py --lock`.",
        "#",
        "# Header `key = value` lines, then one `<sha256>  <relative/path>` line per corpus source,",
        "# sorted by path. This is NOT `exec_snapshots/corpus.lock`: the inherited frozen execution",
        "# corpus is preserved as its own artifact and is not absorbed into this one (§3.2).",
        "#",
        "# A corpus change requires regenerating this file AND bumping corpus_version (§9.6):",
        "# patch = metadata only, minor = new cases/templates/families, major = incompatible",
        "# manifest, protocol or expectation model. `c6_corpus_manifest.rs` enforces the version",
        "# line against a constant, so a regeneration cannot quietly redefine the baseline.",
        "#",
        "# corpus_version 0.1.0 (WP-C6.5-2, 2026-07-26, CD-152): the corpus is created with the",
        "# retained DEV-111/DEV-112 entry-contract cases, so the machinery locks real files rather",
        "# than being vacuously green on an empty tree.",
        f"corpus_version = {CORPUS_VERSION}",
        f"generator_version = {(ROOT / 'generator-version.txt').read_text(encoding='utf-8').strip()}",
        f"generator_seed = {GENERATOR_SEED}",
        f"manifest_sha256 = {sha256(ROOT / 'manifest.toml')}",
        f"generator_sha256 = {sha256(ROOT / 'generate.py')}",
        f"case_count = {len(cases)}",
        f"handwritten_count = {kinds.count('handwritten')}",
        f"generated_count = {kinds.count('generated')}",
        f"retained_count = {kinds.count('retained')}",
        f"metamorphic_group_count = {len(groups)}",
    ]
    for path in sources():
        lines.append(f"{sha256(ROOT / path)}  {path}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] not in ("--lock", "--check"):
        print(__doc__)
        return 2
    lock_path = ROOT / "corpus.lock"
    # `generator_sha256` hashes this script, so writing the lock changes nothing about the script
    # itself — no fixed point to iterate.
    expected = build_lock()
    if sys.argv[1] == "--lock":
        lock_path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {lock_path.relative_to(ROOT)}")
        return 0
    actual = lock_path.read_text(encoding="utf-8") if lock_path.exists() else ""
    if actual != expected:
        print("corpus.lock is stale — run `python3 generate.py --lock`", file=sys.stderr)
        return 1
    print("corpus.lock is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
