#!/usr/bin/env python3
"""WP-C6.5 corpus tool — deterministic case generation (§11) and the corpus lock (§9.5).

    python3 generate.py --list-templates        the template registry and its budgets
    python3 generate.py --write                 (re)generate cases/generated/ + generated.manifest.toml
    python3 generate.py --check                 regenerate into a temp dir and byte-compare
    python3 generate.py --seed S --out DIR      generate under a different seed, elsewhere
    python3 generate.py --lock                  rewrite corpus.lock from the corpus on disk

**Determinism is the whole contract** (§11.2). Selection never depends on process hash
randomisation, dict iteration order, timestamps, PIDs, absolute paths, filesystem order or host
architecture. The algorithm:

  1. enumerate each template's dimension tuples in sorted order;
  2. rank them by `SHA-256(generator_version | seed | template_id | canonical_dimension_tuple)`;
  3. take a fixed budget per template;
  4. derive the case ID from the template plus a digest prefix.

So the same seed and version produce byte-identical output on any machine, and a different seed
produces a different — but equally reproducible — selection.

The lock is regenerated by this script rather than by hand because §9.5 requires per-source hashes
plus counts that must agree with the manifest, and a hand-maintained hash list is one that silently
stops matching. The script hashes ITSELF into the lock, so changing how the corpus is produced
invalidates it.
"""

import hashlib
import pathlib
import shutil
import sys

import metamorphic as metamorphic_registry
import templates as template_registry

ROOT = pathlib.Path(__file__).resolve().parent
CORPUS_VERSION = "1.0.0"
GENERATOR_VERSION = (ROOT / "generator-version.txt").read_text(encoding="utf-8").strip()
DEFAULT_SEED = "c6.5-default"

# §11.4/§11.8 budgets and bounds, recorded here because the plan requires them to be metadata rather
# than folklore. The per-template budget times the registry size is the expected generated count.
PER_TEMPLATE_BUDGET = 5
MAX_SOURCE_BYTES = 4096
MAX_FUNCTIONS_PER_CASE = 8
MAX_LOOP_ITERATIONS = 16
GENERATED_FLOOR = 64


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sources() -> list[str]:
    """Every corpus source, root-relative and sorted. `.stark` only: the manifest, lock, README and
    this script are corpus infrastructure, hashed separately rather than counted as cases."""
    found = [p.relative_to(ROOT).as_posix() for p in ROOT.rglob("*.stark")]
    return sorted(found)


def parse_manifest() -> list[dict]:
    """The same small strict subset the Rust reader accepts (§9.4): `[[case]]` headers and
    `key = "string" | ["a", "b"] | true`. Kept deliberately simple — if this needs a real TOML
    parser, the manifest has outgrown its schema and that is the thing to fix."""
    cases: list[dict] = []
    text = (ROOT / "manifest.toml").read_text(encoding="utf-8")
    generated = ROOT / "generated.manifest.toml"
    if generated.exists():
        text += "\n" + generated.read_text(encoding="utf-8")
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == "[[case]]":
            cases.append({})
            continue
        if " = " not in line:
            raise SystemExit(f"manifest.toml line {number}: not a `key = value` line: {line!r}")
        key, value = line.split(" = ", 1)
        if not cases:
            raise SystemExit(f"manifest.toml line {number}: `{key}` before any [[case]]")
        value = value.strip()
        if value in ("true", "false"):
            cases[-1][key] = value == "true"
        elif value.startswith("[") and value.endswith("]"):
            # Scanned, not split on "," — a value may contain a comma (a rendered array, say), and
            # splitting first would tear it in half. Mirrors `parse_list_items` on the Rust side.
            body, items, rest = value[1:-1].strip(), [], value[1:-1].strip()
            while rest:
                if not rest.startswith('"'):
                    raise SystemExit(f"manifest.toml line {number}: expected a quoted list item")
                end = rest.index('"', 1)
                items.append(rest[1:end])
                rest = rest[end + 1 :].strip().lstrip(",").strip()
            cases[-1][key] = items
        else:
            cases[-1][key] = value.strip('"')
    return cases


# --------------------------------------------------------------- §11 generation --


def canonical_dimensions(dims) -> str:
    """A dimension tuple's canonical text. Deliberately not `repr` or `str` of the tuple: those are
    stable in practice but not contractually, and identity must not drift with a Python release."""
    parts = []
    for item in dims:
        if isinstance(item, (tuple, list)):
            parts.append("(" + ",".join(canonical_dimensions([x]) for x in item) + ")")
        elif isinstance(item, bool):
            parts.append("true" if item else "false")
        else:
            parts.append(str(item))
    return "|".join(parts)


def digest_for(template_id: str, dims, seed: str) -> str:
    material = f"{GENERATOR_VERSION}\x00{seed}\x00{template_id}\x00{canonical_dimensions(dims)}"
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def select(seed: str):
    """Every selected case, in deterministic order: templates sorted by ID, and within a template
    the dimension tuples ranked by digest and truncated to the budget."""
    chosen = []
    for template_id in sorted(template_registry.TEMPLATES):
        build, dimension_space = template_registry.TEMPLATES[template_id]
        ranked = sorted(
            ((digest_for(template_id, dims, seed), dims) for dims in dimension_space),
            key=lambda pair: pair[0],
        )
        if len(ranked) < 3:
            raise SystemExit(
                f"{template_id}: only {len(ranked)} dimension tuples — a template with fewer than "
                f"three instances is not a family, it is a case"
            )
        # R-01: a template whose dimension space IS the coverage claim is taken WHOLE. The budget
        # exists to bound cost where dimensions are interchangeable samples; for T16 each tuple is a
        # distinct normative trap category, so sampling deleted two of them while the corpus still
        # reported full coverage. Cost-bounding must never be able to remove a required observation.
        #
        # Otherwise: up to the budget, and a smaller space contributes all of it rather than being
        # padded with repeats. The §11.4 floor is checked globally, so a shortfall surfaces as "too
        # few cases" rather than as a silently thin template.
        take = (
            len(ranked)
            if template_id in template_registry.EXHAUSTIVE_TEMPLATES
            else min(PER_TEMPLATE_BUDGET, len(ranked))
        )
        for digest, dims in ranked[:take]:
            case = build(dims)
            case_id = f"gen__{template_id.lower()}__{digest[:8]}"
            chosen.append((case_id, template_id, digest, dims, case))
    chosen.sort(key=lambda entry: entry[0])
    # R-11: case IDs are a digest PREFIX, so a collision is improbable rather than impossible. Left
    # undetected it would be silent in the worst way: the second case overwrites the first's file and
    # the manifest carries two entries under one ID, so the corpus quietly loses a case and the
    # validator reports a duplicate long after the cause.
    seen: dict[str, str] = {}
    for case_id, template_id, digest, dims, _case in chosen:
        if case_id in seen:
            raise SystemExit(
                f"case ID collision: {case_id} produced by {seen[case_id]} and by "
                f"{template_id}/{canonical_dimensions(dims)} (digest {digest}). Widen the ID prefix "
                f"or change the dimension; do not let one case overwrite the other."
            )
        seen[case_id] = f"{template_id}/{canonical_dimensions(dims)}"
    return chosen


def enforce_bounds(case_id: str, case) -> None:
    """§11.8: the bounds are tested, not merely declared."""
    size = len(case.source.encode("utf-8"))
    if size > MAX_SOURCE_BYTES:
        raise SystemExit(f"{case_id}: {size} source bytes exceeds the {MAX_SOURCE_BYTES} bound")
    functions = case.source.count("\nfn ") + case.source.startswith("fn ")
    if functions > MAX_FUNCTIONS_PER_CASE:
        raise SystemExit(f"{case_id}: {functions} functions exceeds the {MAX_FUNCTIONS_PER_CASE} bound")
    # R-09: the loop bound is now READ. It was declared and never checked, which is the same as not
    # having one — §11.8 requires bounds to be set AND tested.
    if case.loop_iterations > MAX_LOOP_ITERATIONS:
        raise SystemExit(
            f"{case_id}: {case.loop_iterations} loop iterations exceeds the "
            f"{MAX_LOOP_ITERATIONS} bound"
        )
    if "/" in case_id or "\\" in case_id:
        raise SystemExit(f"{case_id}: a case ID must not contain a path separator")


def manifest_entry(case_id, template_id, digest, dims, case, seed) -> str:
    def lst(items):
        return "[" + ", ".join(f'"{item}"' for item in items) + "]"

    lines = [
        "[[case]]",
        f'case_id = "{case_id}"',
        'kind = "generated"',
        f'category = "{case.category}"',
        f"subcategories = {lst(case.subcategories)}",
        f'sources = ["cases/generated/{case_id}.stark"]',
        'package_graph = "single-file"',
        f'expected_outcome = "{case.expected_outcome}"',
    ]
    if case.expected_trap_category:
        lines.append(f'expected_trap_category = "{case.expected_trap_category}"')
    lines += [
        'required_engines = ["hir", "mir", "native-debug"]',
        'required_targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]',
        f"normative_rules = {lst(case.normative_rules)}",
        f'generator_seed = "{seed}"',
        f'generator_version = "{GENERATOR_VERSION}"',
        f'template_id = "{template_id}"',
    ]
    if case.expected_stdout:
        lines.append(f"expected_stdout = {lst(case.expected_stdout)}")
    if case.drop_protocol:
        lines.append("drop_protocol = true")
        lines.append(f"expected_drop_log = {lst(case.expected_drop_log)}")
    return "\n".join(lines) + "\n"


GENERATED_MANIFEST_HEADER = """# WP-C6.5 GENERATED cases (§11) — written by `generate.py --write`. Do not hand-edit: the next
# regeneration overwrites it, and the corpus lock hashes both this file and the generator.
#
# Hand-authored cases live in `manifest.toml`. The split keeps a regeneration from ever touching a
# case a person wrote, and keeps a person from editing an expectation the generator derived.
#
# Each case's `expected_stdout` / `expected_drop_log` comes from the TEMPLATE's semantic model, not
# from running an engine: the corpus claims the engines agree with the specification, and an
# expectation read back from one of them could only show they agree with each other.
"""


def write_metamorphic(out_root: pathlib.Path) -> list:
    """§13 pairs. Both members of a group are written as ordinary cases carrying family/group
    metadata, so the replay harness runs them like any other case AND the metamorphic harness can
    pair them up. Nothing about a pair is special-cased in the replay — a pair whose members did not
    also individually agree across engines would be meaningless."""
    pairs_dir = out_root / "metamorphic"
    if pairs_dir.exists():
        shutil.rmtree(pairs_dir)
    pairs_dir.mkdir(parents=True)
    def lst(items):
        return "[" + ", ".join(f'"{item}"' for item in items) + "]"

    entries = []
    for group in metamorphic_registry.groups():
        members = (
            (("base", group.base_files), ("transformed", group.transformed_files))
            if group.kind != "source"
            else (("base", group.base), ("transformed", group.transformed))
        )
        for role, payload in members:
            case_id = f"meta__{group.family_id.lower()}_{group.group_id}_{role}"

            if group.kind != "source":
                # A package member is a TREE. Each role gets its own directory, which is also what
                # makes M08 meaningful: the two members are separate physical roots on disk before
                # the harness stages them to two more.
                # Nested under `metamorphic/pkg/` rather than `metamorphic/` because
                # `stage_package` takes the first THREE path components as the tree root to copy
                # (matching `cases/<kind>/<case>`). At `metamorphic/<case>/app` that made `app`
                # itself the root, so staging silently dropped its sibling packages and resolution
                # then failed on a dependency path that "does not exist".
                member_dir = pairs_dir / "pkg" / case_id
                for relative, contents in sorted(payload.items()):
                    target = member_dir / relative
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(contents, encoding="utf-8", newline="\n")
                sources = [
                    f"metamorphic/pkg/{case_id}/{relative}"
                    for relative in sorted(payload)
                    if relative.endswith(".stark")
                ]
                package_root = f"metamorphic/pkg/{case_id}/{group.package_root}"
            else:
                (pairs_dir / f"{case_id}.stark").write_text(
                    payload, encoding="utf-8", newline="\n"
                )
                sources = [f"metamorphic/{case_id}.stark"]
                package_root = None

            body = [
                "[[case]]",
                f'case_id = "{case_id}"',
                'kind = "handwritten"',
                f'category = "{group.category}"',
                # R-13: the FAMILY lives in `metamorphic_family`; `subcategories` is for matrix ROW
                # ids. Writing `M01` here made ten family ids count as covered rows, which is how
                # R-07's coverage number was inflated — and nothing caught it, because nothing
                # checked that a cited row exists.
                f"subcategories = {lst(group.subcategories)}",
                f"sources = {lst(sources)}",
                f'package_graph = "{group.package_graph}"',
                f'expected_outcome = "{"trap" if group.expected_trap else "completion"}"',
                'required_engines = ["hir", "mir", "native-debug"]',
                'required_targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]',
                "normative_rules = ["
                + ", ".join(f'"{rule}"' for rule in group.normative_rules)
                + "]",
                f'metamorphic_family = "{group.family_id}"',
                f'metamorphic_group = "{group.family_id}-{group.group_id}"',
                f'metamorphic_role = "{role}"',
                f'metamorphic_kind = "{group.kind}"',
                f'metamorphic_precondition = "{group.precondition}"',
                "expected_stdout = ["
                + ", ".join(f'"{line}"' for line in group.expected_stdout)
                + "]",
            ]
            if package_root:
                body.append(f'package_root = "{package_root}"')
            if group.expected_drop_log:
                body.append("drop_protocol = true")
                body.append(f"expected_drop_log = {lst(group.expected_drop_log)}")
            if group.expected_trap:
                body.append(f'expected_trap_category = "{group.expected_trap}"')
            if group.pin_canonical_symbols:
                body.append("metamorphic_pin_canonical_symbols = true")
            if group.pin_logical_provenance:
                body.append("metamorphic_pin_logical_provenance = true")
            entries.append((case_id, "\n".join(body) + "\n"))
    return entries


def write_generated(out_root: pathlib.Path, seed: str) -> None:
    cases_dir = out_root / "cases" / "generated"
    if cases_dir.exists():
        shutil.rmtree(cases_dir)
    cases_dir.mkdir(parents=True)
    entries = []
    for case_id, template_id, digest, dims, case in select(seed):
        enforce_bounds(case_id, case)
        (cases_dir / f"{case_id}.stark").write_text(case.source, encoding="utf-8", newline="\n")
        entries.append(manifest_entry(case_id, template_id, digest, dims, case, seed))
    if len(entries) < GENERATED_FLOOR:
        raise SystemExit(
            f"only {len(entries)} generated cases; §11.4's floor is {GENERATED_FLOOR}. Lowering the "
            f"floor needs a recorded rationale, not a quiet edit"
        )
    # Metamorphic members are cases too, and share the generated manifest because both are written
    # by `--write`. Sorted together so the file obeys the manifest's ascending-case_id rule.
    numbered = [(entry.split('case_id = "')[1].split('"')[0], entry) for entry in entries]
    numbered.extend(write_metamorphic(out_root))
    numbered.sort(key=lambda pair: pair[0])
    text = GENERATED_MANIFEST_HEADER + "\n" + "\n".join(entry for _, entry in numbered)
    (out_root / "generated.manifest.toml").write_text(text, encoding="utf-8", newline="\n")


def check_generated() -> int:
    """§11.9: regenerate into a temp directory and byte-compare against what is checked in."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        scratch = pathlib.Path(tmp)
        write_generated(scratch, DEFAULT_SEED)
        drift = []
        checked_in = sorted((ROOT / "cases" / "generated").glob("*.stark")) + sorted(
            (ROOT / "metamorphic").glob("*.stark")
        )
        regenerated = sorted((scratch / "cases" / "generated").glob("*.stark")) + sorted(
            (scratch / "metamorphic").glob("*.stark")
        )
        if [p.name for p in checked_in] != [p.name for p in regenerated]:
            only_in = {p.name for p in checked_in} ^ {p.name for p in regenerated}
            drift.append(f"case set differs: {sorted(only_in)}")
        for path in regenerated:
            mirror = ROOT / path.relative_to(scratch)
            if not mirror.exists() or mirror.read_bytes() != path.read_bytes():
                drift.append(f"{path.name} differs")
        if (ROOT / "generated.manifest.toml").read_bytes() != (
            scratch / "generated.manifest.toml"
        ).read_bytes():
            drift.append("generated.manifest.toml differs")
        if drift:
            print("generated corpus is stale:\n  " + "\n  ".join(drift), file=sys.stderr)
            return 1
    print("generated corpus is current")
    return 0


def list_templates() -> int:
    print(f"generator_version {GENERATOR_VERSION}, default_seed {DEFAULT_SEED}")
    print(f"per-template budget {PER_TEMPLATE_BUDGET}, floor {GENERATED_FLOOR}")
    for template_id in sorted(template_registry.TEMPLATES):
        build, space = template_registry.TEMPLATES[template_id]
        summary = (build.__doc__ or "").strip().splitlines()[0]
        print(f"  {template_id}  {len(space):3d} tuples  {summary}")
    print("not in the registry (recorded, not stubbed):")
    for template_id, why in sorted(template_registry.MISSING_TEMPLATES.items()):
        print(f"  {template_id}  {why}")
    families = {}
    for group in metamorphic_registry.groups():
        families.setdefault(group.family_id, []).append(group.group_id)
    total_groups = sum(len(ids) for ids in families.values())
    print(f"metamorphic: {len(families)} families, {total_groups} groups, {total_groups * 2} members")
    for family, group_ids in sorted(families.items()):
        print(f"  {family}  groups {', '.join(sorted(group_ids))}")
    print("metamorphic families absent (recorded, not approximated):")
    for family, why in sorted(metamorphic_registry.MISSING_FAMILIES.items()):
        print(f"  {family}  {why}")
    return 0


def build_lock() -> str:
    cases = parse_manifest()
    kinds = [case.get("kind", "") for case in cases]
    groups = {case["metamorphic_group"] for case in cases if "metamorphic_group" in case}
    lines = [
        "# WP-C6.5 differential corpus lock (§9.5). Generated by `generate.py --lock`.",
        "#",
        "# Header `key = value` lines, then one `<sha256>  <relative/path>` line per corpus source,",
        "# sorted by path. This is NOT `exec_snapshots/corpus.lock`: the inherited frozen execution",
        "# corpus is preserved as its own artifact and is not absorbed into this one (§3.2).",
        "#",
        "# A corpus change requires regenerating this file AND bumping corpus_version (§9.6):",
        "# patch = metadata only, minor = new cases/templates/families, major = incompatible",
        "# manifest, protocol or expectation model. `c6_corpus_manifest.rs` enforces the version",
        "# line against a constant, so a regeneration cannot quietly redefine the baseline.",
        "#",
        "# corpus_version 0.1.0 (WP-C6.5-2, 2026-07-26, CD-152): the corpus is created with the",
        "# retained DEV-111/DEV-112 entry-contract cases, so the machinery locks real files rather",
        "# than being vacuously green on an empty tree.",
        "# corpus_version 0.2.0 (WP-C6.5-3, 2026-07-26, CD-153): the thirteen §10.3 adversarial",
        "# sentinels, each pinning its observation in the manifest so it fails under the LIKELY WRONG",
        "# implementation rather than only under engine disagreement. Minor: new cases, no change to",
        "# any existing source or expectation.",
        "# corpus_version 0.3.0 (WP-C6.5-4, 2026-07-26, CD-155): the deterministic generator and its",
        "# 70 cases across 15 templates. `generator_sha256` and `templates_sha256` pin the producer as",
        "# well as the product -- regenerating with a changed template changes the lock. Minor.",
        "# corpus_version 0.4.0 (WP-C6.5-6, 2026-07-26, CD-157): 20 metamorphic groups over ten of the",
        "# twelve §13.1 families, 40 member cases. M08/M09 transform a package graph and are absent",
        "# until §15 rather than approximated single-file. Minor.",
        "# corpus_version 1.0.0 (WP-C6.5 closure, 2026-07-28, CD-173): the corpus the closure",
        "# packet cites. All thirteen \u00a717 findings closed; 153 cases; 24 metamorphic groups across",
        "# twelve families; 10 of 10 admitted trap categories; every one of the 136 coverage-matrix",
        "# rows carrying one machine-checked disposition. 1.0.0 is a FREEZE marker, not a claim of",
        "# completeness -- DEV-116 and DEV-117 are open blockers recorded against it.",
        "# corpus_version 0.11.0 (batch, 2026-07-28, CD-171): R-07 closed. Eight handwritten cases",
        "# for the rows that had no comparator-backed evidence at all -- unary/bitwise/casts,",
        "# statements and `loop`, tuple and array patterns, Float64, Copy/move, Drop order and the",
        "# active enum payload, explicit-vs-inferred type args, and array element consumption.",
        "# Writing them found DEV-117 (MIR refuses reinitialisation). Minor.",
        "# corpus_version 0.10.0 (batch, 2026-07-28, CD-170): R-07. T16 now CITES every trap-",
        "# category row its emitted sources actually raise (X02-X09, X12), verified against the",
        "# bodies rather than asserted. X13 is deliberately excluded: T16 declares no `Drop` type,",
        "# so it cannot witness the ABSENCE of cleanup. Metadata only. Minor.",
        "# corpus_version 0.9.0 (batch, 2026-07-27, CD-167): R-04/R-05. M08 (workspace relocation)",
        "# and M09 (dependency declaration reorder) are BUILT, reaching \u00a713.2's floor of 24 groups /",
        "# 48 members across all twelve families. Both were recorded as unbuildable -- 'every corpus",
        "# case is single-file until \u00a715' -- which stopped being true when DEV-113/DEV-114 added",
        "# package cases, and DEV-114's fix is what made M09 comparable at all. Four new package",
        "# member trees. Minor.",
        "# corpus_version 0.8.0 (batch, 2026-07-27, CD-165): R-07. Eleven matrix rows the generated",
        "# cases genuinely exercise are now CITED by the templates that exercise them, verified",
        "# against the emitted sources. Paired with the matrix correction of 36 unearned `->T##`",
        "# arrows and a test that reads every remaining arrow. Metadata only -- no case source",
        "# changed -- but the coverage claim did, so: minor.",
        "# corpus_version 0.7.0 (batch, 2026-07-27, CD-165): R-01/R-09/R-11/R-13. T16 is EXHAUSTIVE",
        "# (its dimension space IS the coverage claim, so a sampling budget must not truncate it) and",
        "# gains UnwrapNone/UnwrapErr -- 10 of 10 admitted trap categories. The loop bound is enforced,",
        "# case-ID collisions are detected, and metamorphic members no longer cite family ids as if",
        "# they were matrix rows. Minor.",
        "# corpus_version 0.6.0 (batch, 2026-07-27, CD-164): the three approved decision packets.",
        "# DEV-113 makes package trap provenance logical, which admits the dependency-trap case §15.1",
        "# requires; the CD-150 CE3 adds TrapCategory::InvalidExitStatus (MIR amendment A7) and native",
        "# emission for every PROC-MAIN-001 entry signature, so the entry cases become three-engine and",
        "# the out-of-range status joins as a trap case. Trap coverage 5 of 9 -> 7 of 9. Minor.",
        "# corpus_version 1.0.0 (WP-C6.5 closure, 2026-07-28, CD-173): the corpus the closure",
        "# packet cites. All thirteen \u00a717 findings closed; 153 cases; 24 metamorphic groups across",
        "# twelve families; 10 of 10 admitted trap categories; every one of the 136 coverage-matrix",
        "# rows carrying one machine-checked disposition. 1.0.0 is a FREEZE marker, not a claim of",
        "# completeness -- DEV-116 and DEV-117 are open blockers recorded against it.",
        "# corpus_version 0.11.0 (batch, 2026-07-28, CD-171): R-07 closed. Eight handwritten cases",
        "# for the rows that had no comparator-backed evidence at all -- unary/bitwise/casts,",
        "# statements and `loop`, tuple and array patterns, Float64, Copy/move, Drop order and the",
        "# active enum payload, explicit-vs-inferred type args, and array element consumption.",
        "# Writing them found DEV-117 (MIR refuses reinitialisation). Minor.",
        "# corpus_version 0.10.0 (batch, 2026-07-28, CD-170): R-07. T16 now CITES every trap-",
        "# category row its emitted sources actually raise (X02-X09, X12), verified against the",
        "# bodies rather than asserted. X13 is deliberately excluded: T16 declares no `Drop` type,",
        "# so it cannot witness the ABSENCE of cleanup. Metadata only. Minor.",
        "# corpus_version 0.9.0 (batch, 2026-07-27, CD-167): R-04/R-05. M08 (workspace relocation)",
        "# and M09 (dependency declaration reorder) are BUILT, reaching \u00a713.2's floor of 24 groups /",
        "# 48 members across all twelve families. Both were recorded as unbuildable -- 'every corpus",
        "# case is single-file until \u00a715' -- which stopped being true when DEV-113/DEV-114 added",
        "# package cases, and DEV-114's fix is what made M09 comparable at all. Four new package",
        "# member trees. Minor.",
        "# corpus_version 0.8.0 (batch, 2026-07-27, CD-165): R-07. Eleven matrix rows the generated",
        "# cases genuinely exercise are now CITED by the templates that exercise them, verified",
        "# against the emitted sources. Paired with the matrix correction of 36 unearned `->T##`",
        "# arrows and a test that reads every remaining arrow. Metadata only -- no case source",
        "# changed -- but the coverage claim did, so: minor.",
        "# corpus_version 0.7.0 (batch, 2026-07-27, CD-165): R-01/R-09/R-11/R-13. T16 is EXHAUSTIVE",
        "# (its dimension space IS the coverage claim, so a sampling budget must not truncate it) and",
        "# gains UnwrapNone/UnwrapErr -- 10 of 10 admitted trap categories. The loop bound is enforced,",
        "# case-ID collisions are detected, and metamorphic members no longer cite family ids as if",
        "# they were matrix rows. Minor.",
        "# corpus_version 0.6.0 (batch, 2026-07-27, CD-164): the three approved decision packets.",
        "# DEV-113 makes package trap provenance logical, which admits the dependency-trap case §15.1",
        "# requires; the CD-150 CE3 adds TrapCategory::InvalidExitStatus (MIR amendment A7) and native",
        "# emission for every PROC-MAIN-001 entry signature, so the entry cases become three-engine and",
        "# the out-of-range status joins as a trap case. Trap coverage 5 of 9 -> 7 of 9. Minor.",
        "# corpus_version 0.5.0 (WP-C6.5-8, 2026-07-27, CD-159): the first PACKAGE cases -- a root",
        "# package with a module, and a three-package workspace exercising a dependency-to-dependency",
        "# call, a re-export, a cross-package generic and a cross-package Drop. Minor.",
        f"corpus_version = {CORPUS_VERSION}",
        f"generator_version = {(ROOT / 'generator-version.txt').read_text(encoding='utf-8').strip()}",
        f"generator_seed = {DEFAULT_SEED}",
        f"manifest_sha256 = {sha256(ROOT / 'manifest.toml')}",
        f"generated_manifest_sha256 = {sha256(ROOT / 'generated.manifest.toml')}",
        f"templates_sha256 = {sha256(ROOT / 'templates.py')}",
        f"metamorphic_sha256 = {sha256(ROOT / 'metamorphic.py')}",
        f"generator_sha256 = {sha256(ROOT / 'generate.py')}",
        f"case_count = {len(cases)}",
        f"handwritten_count = {kinds.count('handwritten')}",
        f"generated_count = {kinds.count('generated')}",
        f"retained_count = {kinds.count('retained')}",
        f"metamorphic_group_count = {len(groups)}",
    ]
    for path in sources():
        lines.append(f"{sha256(ROOT / path)}  {path}")
    return "\n".join(lines) + "\n"


def self_test_guards() -> int:
    """Negative controls for the two guards §17 added (R-09, R-11).

    A guard that has never refused anything is a guard nobody has watched work. This mode forces
    each failure deliberately and requires the generator to reject it; `c6_corpus_generator.rs` runs
    it and asserts a non-zero exit with the expected reason.
    """
    failures = []

    # R-11: two dimension tuples forced to the same case ID.
    original_digest = globals()["digest_for"]
    globals()["digest_for"] = lambda template_id, dims, seed: "c0111de" + "d" * 57
    try:
        select(DEFAULT_SEED)
        failures.append("collision was NOT detected")
    except SystemExit as refusal:
        if "case ID collision" not in str(refusal):
            failures.append(f"collision refused for the wrong reason: {refusal}")
    finally:
        globals()["digest_for"] = original_digest

    # R-09: a case declaring more loop iterations than the bound allows.
    over = template_registry.Case(
        source="fn main() {}\n",
        category="control-transfer",
        subcategories=(),
        normative_rules=("EXEC-CFLOW-001",),
        loop_iterations=MAX_LOOP_ITERATIONS + 1,
    )
    try:
        enforce_bounds("probe", over)
        failures.append("the loop bound was NOT enforced")
    except SystemExit as refusal:
        if "loop iterations exceeds" not in str(refusal):
            failures.append(f"loop bound refused for the wrong reason: {refusal}")

    # R-04/R-05: the kind-aware metamorphic guards. Driven through the REAL
    # `validate_package_pair` rather than a copy of its rules — a self-test that reimplements the
    # guard proves the copy works.
    diamond = metamorphic_registry.DIAMOND_WORKSPACE
    reordered = metamorphic_registry.reorder_dependencies(diamond, "app/starkpkg.json")
    edited = dict(diamond)
    edited["base/src/main.stark"] = edited["base/src/main.stark"].replace("v * 2", "v * 3")
    narrowed = dict(diamond)
    narrowed["app/starkpkg.json"] = metamorphic_registry._manifest("app", ["left"])
    reordered_and_edited = dict(reordered)
    reordered_and_edited["base/src/main.stark"] = edited["base/src/main.stark"]

    for what, kind, base, transformed, wanted in [
        (
            "a relocation pair whose trees differ",
            "relocation", diamond, edited, "must keep every logical file",
        ),
        (
            "a reorder that also edits a source file",
            "dependency-reorder", diamond, reordered_and_edited, "only MANIFESTS may differ",
        ),
        (
            "a reorder that changes the dependency SET",
            "dependency-reorder", diamond, narrowed, "changed the dependency SET",
        ),
        (
            "a reorder that reordered nothing",
            "dependency-reorder", diamond, dict(diamond), "reordered nothing",
        ),
        (
            "an unknown transformation kind",
            "teleportation", diamond, reordered, "unknown package transformation kind",
        ),
    ]:
        try:
            metamorphic_registry.validate_package_pair("MX", "probe", kind, base, transformed)
            failures.append(f"{what} was ACCEPTED")
        except AssertionError as refusal:
            if wanted not in str(refusal):
                failures.append(f"{what} refused for the wrong reason: {refusal}")

    if failures:
        for failure in failures:
            print(f"guard self-test FAILED: {failure}", file=sys.stderr)
        return 1
    print(
        "guard self-tests pass: collision, loop bound, and five metamorphic package-pair rules all "
        "refuse"
    )
    return 0


def main() -> int:
    argv = sys.argv[1:]
    if argv[:1] == ["--self-test-guards"]:
        return self_test_guards()
    if argv[:1] == ["--list-templates"]:
        return list_templates()
    if argv[:1] == ["--write"]:
        write_generated(ROOT, DEFAULT_SEED)
        print(f"wrote cases/generated/ and generated.manifest.toml (seed {DEFAULT_SEED})")
        return 0
    if argv[:1] == ["--check"]:
        return check_generated()
    if len(argv) == 4 and argv[0] == "--seed" and argv[2] == "--out":
        out = pathlib.Path(argv[3])
        out.mkdir(parents=True, exist_ok=True)
        write_generated(out, argv[1])
        print(f"wrote {out} (seed {argv[1]})")
        return 0
    if argv != ["--lock"]:
        print(__doc__)
        return 2
    lock_path = ROOT / "corpus.lock"
    # `generator_sha256` hashes this script, so writing the lock changes nothing about the script
    # itself — no fixed point to iterate.
    lock_path.write_text(build_lock(), encoding="utf-8", newline="\n")
    print(f"wrote {lock_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
